"Types of Data ranges for the alarm report response"
enum DashBoardDevicesAlarmReportTimeRangeType{
  "Last hour"
  ONE_HOUR,
  "Last two hours"
  TWO_HOURS,
  "Last three hours"
  THREE_HOURS
}
"type of network status"
enum DeviceNetworkStatus{
  "online status"
  ONLINE,
  "offline status"
  OFFLINE
}
"Types of alarm reports"
enum DashBoardDevicesAlarmReportType{
  "Ram usage alarms"
  RAM_MEMORY,
  "CPU usage alarms"
  CPU_USAGE,
  "Voltage alarms"
  VOLTAGE,
  "Device temperature alarms"
  TEMPERATURE
}

"Top n Devices list for the DashBoardDevicesAlarmReport"
type DashBoardDevicesAlarmReportTopDevices{
  "device Serial Number"
  sn: String!
  "Device hostname"
  hostname: String!
  "Number of alarms reported by the device"
  alarmsCount: Int!
  "Link to navigate to the device info page"
  deviceDetailLink: String
}

"TimeRange description DashBoardDevicesAlarmReportTimeRange"
type DashBoardDevicesAlarmReportTimeRange{
    "Time range type"
    timeRange: DashBoardDevicesAlarmReportTimeRangeType!
    "Total alarm count"
    alarmsCount: Int!
    "Total number of alarmed devices"
    devicesCount: Int!
    "Order within list, lowest is first"
    order: Int!
    "Top alarmed devices "
    topDevices: [DashBoardDevicesAlarmReportTopDevices]
    "Link to browse all the alarmed devices"
    fullDevicesListLink: String
  }

"Alarm report type used for DashBoardDevices"
type DashBoardDevicesAlarmReport {
  "Report type"
  type: DashBoardDevicesAlarmReportType!
  "Time ranges"
  timeRanges: [DashBoardDevicesAlarmReportTimeRange]
}

"Device Network status event type used for DashBoardDevices"
type DashBoardDevicesNetworkEvent{
  "Network status"
  state: DeviceNetworkStatus!
  "Serial of device"
  serial: String!
  "hostname of device"
  hostname: String!
  "Cuenca to Device belongs"
  cuenca: String!
}

"Object used to represents data on Dashboard chart"
type DashBoardDeviceNetworkStatusSubSerie{
  "serie name"
  name: String!
  "serie value"
  value: Int!
}

type DashBoardDeviceNetworkStatus{
  "Cuenca name used to show in devices on Vs devices off chart"
  name: String!
  series: [DashBoardDeviceNetworkStatusSubSerie]!
}

type DashboardDeviceTransaction{
  "Device transactions group by interval and groupName"
  interval: BigInt!
  groupName: String
  transactions: Int!
  errors: Int!
}

type DashboardDeviceTransactionSucess{
  "Device sucessfull transactions group and groupName"
  name: String!
  value: Int!
}
type DashboardDeviceTransactionSucessArray{
  timeRange: DashBoardDevicesAlarmReportTimeRangeType!
  data: [DashboardDeviceTransactionSucess]!
}


type DeviceTransactionsUpdatedEvent{
  "Event that informs when it's necessary to update the device transaction stats"
  timestamp: BigInt!
}

type Query {
  "Get a report summary of alarmed devices.  this is used on DashBoardDevices section"
  getDashBoardDevicesAlarmReport(type: DashBoardDevicesAlarmReportType!): DashBoardDevicesAlarmReport
  getDashBoardDevicesCurrentNetworkStatus: [DashBoardDeviceNetworkStatus]!
  getCuencaNamesWithSuccessTransactionsOnInterval(startDate: BigInt, endDate: BigInt): [String]!
  getSucessDeviceTransactionsGroupByGroupName: [DashboardDeviceTransactionSucessArray]!
  getDeviceTransactionsGroupByTimeInterval(startDate: BigInt, endDate: BigInt, groupName: String): [DashboardDeviceTransaction]!
  getDeviceDashBoardTotalAccount: Int!
  
}

type Subscription {
  onDashBoardDeviceOnlineReported: [DashBoardDeviceNetworkStatus]!
  onDashBoardDeviceOfflineReported: [DashBoardDeviceNetworkStatus]!
  onDashBoardDeviceCpuUsageAlarmActivated: DashBoardDevicesAlarmReport!
  onDashBoardDeviceRamMemoryAlarmActivated: DashBoardDevicesAlarmReport!
  onDashBoardDeviceTemperatureAlarmActivated: DashBoardDevicesAlarmReport!
  onDashBoardDeviceLowVoltageAlarmReported: DashBoardDevicesAlarmReport!
  onDashBoardDeviceHighVoltageAlarmReported: DashBoardDevicesAlarmReport!
  deviceTransactionsUpdatedEvent: DeviceTransactionsUpdatedEvent!
}